### ISSUE TITLE
Create a git tag

### ISSUE THREAD

**Issue by dpassen** [athos/clj-check#10]
Today's release of the Clojure CLI Tool, 1.10.3.933 https://clojure.org/releases/tools#v1.10.3.933 offers a new way to refer to a git lib, by means of short sha and a tag. It would be nice to tag the repository so we may make use of it.

**Comment by athos** [comment]
Yeah, that would be nice 👍  I'll add a tag to the latest commit later.
Also, I'm going to update the README as well in a couple of days to mention installation via the new format of git coord.

**Comment by dpassen** [comment]
Here’s how I’m using it now: https://github.com/dpassen/dotfiles/blob/56983b6b4b623aee6603f8ea4e1228d880efeb5e/clojure/deps.edn#L8-L13

**Comment by dpassen** [comment]
Unsure if it _should_ be com.github.athos vs. io.github.athos

**Comment by dpassen** [comment]
Decided on io

**Comment by NoahTheDuke** [comment]
any update on this?

**Comment by athos** [comment]
Sorry for not being able to comment! I've been swamped with parenting duties recently and haven't had much time to maintain my libraries...

The tag [0.1.0](https://github.com/athos/clj-check/releases/tag/0.1.0) should already be available, but updating the README has been on the back burner. I'll make sure to get to it as soon as I find some time.

**Comment by athos** [comment]
Sorry for the terrible delay since my last comment... I just updated the README in d997df866b2a04b7ce7b17533093ee0a2e2cb729.
