### ISSUE TITLE
[bug] Clojure command line tools no longer accept unqualified library dependencies

### ISSUE THREAD

**Issue by pmonks** [athos/clj-check#5]
### Steps to reproduce:
1. upgrade to latest version of Clojure CLI tools (reproduced with v1.10.1.590)
2. have a `deps.edn` with `athos/clj-check` configured e.g.:
```edn
{
  :aliases {
    :check {
      :extra-deps {athos/clj-check {:git/url "https://github.com/athos/clj-check.git" :sha "a2f4d4cb6ef347bff420edb66629e41d530b9668"}}
      :main-opts  ["-m" "clj-check.check"]}}}
```
3. run the alias: `clj -A:check`

### Expected result:
Checking is performed without warnings.

### Actual result:
Following warning is emitted by Clojure CLI tools:
```
DEPRECATED: Libs must be qualified, change bultitude => bultitude/bultitude (/Users/pmonks/.gitlibs/libs/athos/clj-check/a2f4d4cb6ef347bff420edb66629e41d530b9668/deps.edn)
DEPRECATED: Libs must be qualified, change bultitude => bultitude/bultitude (/Users/pmonks/.gitlibs/libs/athos/clj-check/a2f4d4cb6ef347bff420edb66629e41d530b9668/deps.edn)
```

**Comment by athos** [comment]
Thank you for filing the issue! I wasn't aware of that update since I didn't use the devel version of Clojure CLI.
Now I can reproduce it with the latest CLI, so I will fix it later on.

**Comment by pmonks** [comment]
No worries!  I only happened to stumble upon it today, after homebrew updated my Clojure CLI version.
